version: '3.8'

services:
  web:
    build: .
    container_name: deposite_service
    command: >
        bash -c "gunicorn app.main:application --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
        api_network:


networks:
  api_network:


  # main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80

  